create table tb_feedback (
	id BIGINT NOT NULL COMMENT 'ID',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	version INT NOT NULL DEFAULT 0 COMMENT '版本号',
	deleted VARCHAR(10) NOT NULL DEFAULT 'NO' COMMENT '删除状态',
	content VARCHAR(500) NOT NULL COMMENT '账号',
    user_id BIGINT NOT NULL COMMENT '用户id',
    type VARCHAR(20) NOT NULL DEFAULT 'BUG' COMMENT '注册方式',
    media VARCHAR(5000)  COMMENT '媒体',
    state VARCHAR(20) NOT NULL DEFAULT 'UNPROCESSED' COMMENT '处理状态',
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户反馈表';