create table tb_media (
	id BIGINT NOT NULL COMMENT 'ID',
	create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	version INT NOT NULL DEFAULT 0 COMMENT '版本号',
	deleted VARCHAR(10) NOT NULL DEFAULT 'NO' COMMENT '删除状态',
	resource_id BIGINT NOT NULL COMMENT '源数据ID',
	cover VARCHAR(500)  COMMENT '媒体封面',
	type VARCHAR(20) NOT NULL  COMMENT '媒体类型',
	duration INT COMMENT '时长',
    url  VARCHAR(500)  COMMENT '媒体链接',
    content VARCHAR(500) COMMENT '描述内容',
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='媒体资源表';