spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/heyya?useSSL=false&characterEncoding=utf-8&useUnicode=true&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: root
  liquibase:
    change-log: classpath:liquibase/master.xml
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0

mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
  row-bounds-with-count: true
  