server:
  shutdown: graceful
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: text/plain,text/xml,application/xml,application/json
  port: 8200
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: heyya-client-api
  profiles:
    active: local

user-auth:
  token-expire: 31536000
  exclude-path-patterns:
    - /swagger-resources/**
    - /webjars/**
    - /v2/**
    - /swagger-ui.html/**
    - /doc.html/**
    - /error
    - /metrics/prometheus
    - /favicon.ico
    - /v3/api-docs
    - /swagger-ui/index.html/**
    - /v1/sing-in
    - /v1/sub/email
